version: '3'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      MONGO_URI: 'mongodb://mongo:27017/url-shortner'
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
